// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NpApi.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NpApi.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924224024_AddPlaces")]
    partial class AddPlaces
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NpApi.Api.Features.People.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("middle_name");

                    b.HasKey("Id")
                        .HasName("pk_people");

                    b.HasIndex("FirstName", "LastName")
                        .HasDatabaseName("ix_people_first_name_last_name");

                    b.ToTable("people", null, t =>
                        {
                            t.HasCheckConstraint("ck_people_first_name_not_blank", "btrim(first_name) <> ''");
                        });
                });

            modelBuilder.Entity("NpApi.Api.Features.Photos.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CameraOwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("camera_owner_id");

                    b.Property<string>("CloudinaryPublicId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cloudinary_public_id");

                    b.Property<string>("DateCategory")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("date_category");

                    b.Property<DateTimeOffset?>("DateTaken")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_taken");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("filename");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationSource")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("location_source");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<Guid?>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("uploaded_by");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("url");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_photos");

                    b.HasIndex("CameraOwnerId")
                        .HasDatabaseName("ix_photos_camera_owner_id");

                    b.HasIndex("CloudinaryPublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_photos_cloudinary_public_id");

                    b.HasIndex("DateTaken")
                        .HasDatabaseName("ix_photos_date_taken");

                    b.HasIndex("PlaceId")
                        .HasDatabaseName("ix_photos_place_id");

                    b.HasIndex("Tags")
                        .HasDatabaseName("ix_photos_tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "gin");

                    b.ToTable("photos", null, t =>
                        {
                            t.HasCheckConstraint("ck_photos_latitude_range", "latitude BETWEEN -90 AND 90");

                            t.HasCheckConstraint("ck_photos_location_complete", "(latitude IS NULL) = (longitude IS NULL) AND (latitude IS NULL) = (location_source IS NULL)");

                            t.HasCheckConstraint("ck_photos_longitude_range", "longitude BETWEEN -180 AND 180");
                        });
                });

            modelBuilder.Entity("NpApi.Api.Features.Photos.PhotoPerson", b =>
                {
                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uuid")
                        .HasColumnName("photo_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateTimeOffset>("TaggedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tagged_at");

                    b.Property<string>("TaggedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tagged_by");

                    b.HasKey("PhotoId", "PersonId")
                        .HasName("pk_photo_people");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_photo_people_person_id");

                    b.ToTable("photo_people", (string)null);
                });

            modelBuilder.Entity("NpApi.Api.Features.Places.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("code")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Code")
                        .HasName("pk_countries");

                    b.ToTable("countries", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "US",
                            Name = "United States"
                        },
                        new
                        {
                            Code = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            Code = "MX",
                            Name = "Mexico"
                        });
                });

            modelBuilder.Entity("NpApi.Api.Features.Places.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("StateProvince")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("state_province");

                    b.HasKey("Id")
                        .HasName("pk_places");

                    b.HasIndex("CountryCode", "StateProvince", "City")
                        .HasDatabaseName("ix_places_country_code_state_province_city");

                    b.ToTable("places", null, t =>
                        {
                            t.HasCheckConstraint("ck_places_latitude_range", "latitude BETWEEN -90 AND 90");

                            t.HasCheckConstraint("ck_places_longitude_range", "longitude BETWEEN -180 AND 180");

                            t.HasCheckConstraint("ck_places_not_empty", "city IS NOT NULL OR state_province IS NOT NULL OR country_code IS NOT NULL OR latitude IS NOT NULL");

                            t.HasCheckConstraint("ck_places_point_complete", "(latitude IS NULL) = (longitude IS NULL)");
                        });
                });

            modelBuilder.Entity("NpApi.Api.Features.Photos.Photo", b =>
                {
                    b.HasOne("NpApi.Api.Features.People.Person", "CameraOwner")
                        .WithMany()
                        .HasForeignKey("CameraOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_photos_people_camera_owner_id");

                    b.HasOne("NpApi.Api.Features.Places.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_photos_places_place_id");

                    b.Navigation("CameraOwner");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("NpApi.Api.Features.Photos.PhotoPerson", b =>
                {
                    b.HasOne("NpApi.Api.Features.People.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_photo_people_people_person_id");

                    b.HasOne("NpApi.Api.Features.Photos.Photo", "Photo")
                        .WithMany("TaggedPeople")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_photo_people_photos_photo_id");

                    b.Navigation("Person");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("NpApi.Api.Features.Places.Place", b =>
                {
                    b.HasOne("NpApi.Api.Features.Places.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_places_countries_country_code");
                });

            modelBuilder.Entity("NpApi.Api.Features.Photos.Photo", b =>
                {
                    b.Navigation("TaggedPeople");
                });
#pragma warning restore 612, 618
        }
    }
}
